/**
 * Phase B / S50 — tenant-scoped storage path helper + audited upload wrapper.
 * S102 — staging + sources path helpers for the file-upload feature.
 *
 * Lives in `agent/lib/storage-paths.ts`. The frontend uses a mirror at
 * `frontend/lib/storage-paths.ts` (path helpers only — no audit wrapper, since
 * the frontend's only writes are attachment staging/copy via signed URLs).
 *
 * Path layout (post-Phase-B migration):
 *   <organization_id>/<project_slug>/<file>            deliverables
 *   <organization_id>/<project_slug>/sources/<file>    user attachments (S102)
 *   <organization_id>/uploads/<draft_id>/<file>        attachment staging (S102)
 *
 * Pre-Phase-B (legacy) layout was flat: <project_slug>/<file>. The migration
 * script `phase-b-migrate-storage-paths.ts` COPIES legacy objects to the new
 * layout. After migration, code MUST construct paths via the helpers below
 * — never directly concatenate slug + file. The grep CI test in
 * `test-phase-b-storage-paths.sh` enforces this at build time.
 *
 * Exports:
 *   - scopedStoragePath(orgId, projectSlug, file?) — pure path construction.
 *     Throws on invalid orgId (uuid regex), slug containing path-traversal
 *     components, or file containing path-traversal components.
 *   - scopedStagingPath(orgId, draftId, file?) — S102 attachment staging.
 *   - scopedSourcesPath(orgId, projectSlug, file) — S102 submitted attachments.
 *   - uploadWithAudit(opts) — wraps supabase storage.upload() + best-effort
 *     append to public.audit_storage_writes. Audit failure is logged but
 *     NEVER blocks the upload (per v3 plan §2.5.5).
 */

import type { SupabaseClient } from "@supabase/supabase-js";
import { ATTACHMENTS, BUCKET } from "./conventions.js";

// Canonical UUID SHAPE (8-4-4-4-12 hex). v1 of this helper used a looser
// 36-hex-with-dashes match (no layout enforcement) which accepted
// pathological strings like 36 consecutive hyphens. Enforce the canonical
// layout so downstream code never has to second-guess the helper. (S50
// Gemini MERGE M1.) NOTE: shape only — the version/variant nibbles are NOT
// pinned to v4 (S102 interim-review MINOR; renamed from UUID_V4_REGEX whose
// name overclaimed). All real ids here are v4 (gen_random_uuid() /
// crypto.randomUUID()), but the helper accepts any well-shaped UUID.
const UUID_SHAPE_REGEX = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

// S102 — compiled storedName contract for attachment files (canonical
// pattern string lives in conventions.json attachments.stored_name_regex;
// frontend mirror: ATTACHMENT_STORED_NAME_REGEX in attachments-constants.ts).
// The staging/sources helpers enforce this on their `file` param so the
// docstring claim "re-rejects traversal at every path construction" is
// actually true for leading-dot, control-char, and wrong-extension names —
// not just `/ \ ..` (S102 interim-review MINOR: a future mis-wire passing
// the unsanitized originalName must throw here, not corrupt the namespace).
const STORED_NAME_REGEX = new RegExp(ATTACHMENTS.stored_name_regex);

/**
 * Construct a tenant-scoped storage path.
 *
 * @param orgId        organizations.id (uuid v4)
 * @param projectSlug  research_queue.topic_slug (no path separators, no `..`)
 * @param file         optional filename (no path separators, no `..` traversal)
 * @returns            `<orgId>/<slug>` or `<orgId>/<slug>/<file>`
 * @throws on invalid orgId format, slug containing path-traversal components,
 *         or file containing path-traversal components (S50 Gemini MERGE C1 +
 *         S56 Codex C-m1 — defense in depth even where callers also validate).
 */
export function scopedStoragePath(
  orgId: string,
  projectSlug: string,
  file?: string,
): string {
  if (!orgId || !UUID_SHAPE_REGEX.test(orgId)) {
    throw new Error(`scopedStoragePath: invalid orgId "${orgId}"`);
  }
  // Slug validation symmetric with filename validation below: reject "/",
  // "\", and ".." path-traversal components. The helper is the
  // tenant-boundary primitive; defense-in-depth even though slugs are
  // generated by generateSlug() today (Codex round-2 MINOR finding C-m1,
  // S56). Pair-edited with frontend/lib/storage-paths.ts.
  if (
    !projectSlug ||
    projectSlug.includes("/") ||
    projectSlug.includes("\\") ||
    projectSlug.includes("..")
  ) {
    throw new Error(`scopedStoragePath: invalid slug "${projectSlug}"`);
  }
  if (file && (file.includes("/") || file.includes("\\") || file.includes(".."))) {
    throw new Error(`scopedStoragePath: invalid file name components "${file}"`);
  }
  return file ? `${orgId}/${projectSlug}/${file}` : `${orgId}/${projectSlug}`;
}

// ── S102 attachment path helpers ────────────────────────────────────

/**
 * Construct a tenant-scoped STAGING path for a not-yet-submitted attachment.
 *
 * Layout: `<orgId>/uploads/<draftId>` or `<orgId>/uploads/<draftId>/<file>`.
 * The "uploads" segment (ATTACHMENTS.staging_prefix) can never collide with a
 * real topic_slug because generateSlug() always appends "-<8 hex>". draftId is
 * a client-generated UUID v4 (crypto.randomUUID()) scoping concurrent drafts;
 * the orgId prefix means a caller can only ever stage into (and copy out of)
 * its own org. Staged objects older than ATTACHMENTS.staging_ttl_hours are
 * garbage by construction — submit copies out of staging synchronously
 * BEFORE inserting the queue row.
 */
export function scopedStagingPath(
  orgId: string,
  draftId: string,
  file?: string,
): string {
  if (!orgId || !UUID_SHAPE_REGEX.test(orgId)) {
    throw new Error(`scopedStagingPath: invalid orgId "${orgId}"`);
  }
  if (!draftId || !UUID_SHAPE_REGEX.test(draftId)) {
    throw new Error(`scopedStagingPath: invalid draftId "${draftId}"`);
  }
  if (file && (!STORED_NAME_REGEX.test(file) || file.includes(".."))) {
    throw new Error(`scopedStagingPath: invalid attachment file name "${file}"`);
  }
  const prefix = `${orgId}/${ATTACHMENTS.staging_prefix}/${draftId}`;
  return file ? `${prefix}/${file}` : prefix;
}

/**
 * Construct the tenant-scoped SOURCES path for a submitted run's attachment.
 *
 * Layout: `<orgId>/<slug>/sources/<file>`. The sources/ subdir is invisible
 * to the gallery (frontend lib/storage.ts listFiles filters sub-folders) and
 * to uploadOutputs (agent/lib/upload-set.ts excludes subdirectories), so
 * attachments never pollute the run's deliverables list and are never
 * re-uploaded at job end. Org/slug validation is delegated to
 * scopedStoragePath; `file` is REQUIRED (a bare sources/ dir is never a
 * valid storage object target).
 */
export function scopedSourcesPath(
  orgId: string,
  projectSlug: string,
  file: string,
): string {
  const base = scopedStoragePath(orgId, projectSlug);
  if (!file || !STORED_NAME_REGEX.test(file) || file.includes("..")) {
    throw new Error(`scopedSourcesPath: invalid attachment file name "${file}"`);
  }
  return `${base}/${ATTACHMENTS.sources_subdir}/${file}`;
}

// ── Audited upload wrapper ──────────────────────────────────────────

export interface UploadWithAuditOpts {
  sb: SupabaseClient;
  /** Source filename, e.g. "executor.ts". Goes into audit_storage_writes.caller. */
  caller: string;
  organizationId: string;
  /** research_queue.id for the run this upload belongs to. Null if standalone. */
  researchQueueId: string | null;
  projectSlug: string;
  filename: string;
  content: Buffer;
  contentType: string;
  upsert: boolean;
}

export interface UploadWithAuditResult {
  ok: boolean;
  /** The full bucket path the upload targeted (whether successful or not). */
  path: string;
  /** Set only on failure. */
  reason?: string;
}

/**
 * Upload a single object to the research-projects bucket and append a row to
 * public.audit_storage_writes capturing caller/org/queue/path/bytes/status.
 *
 * Per v3 plan §2.5.5: the audit row write is best-effort. Failure is logged
 * to stdout but does not block the caller — audit must never be a single
 * point of failure that prevents legitimate uploads.
 *
 * Returns { ok, path, reason? } so callers can fail-loud on real upload
 * failures while staying ignorant of audit-row plumbing.
 */
export async function uploadWithAudit(
  opts: UploadWithAuditOpts,
): Promise<UploadWithAuditResult> {
  const objectPath = scopedStoragePath(
    opts.organizationId,
    opts.projectSlug,
    opts.filename,
  );

  const { error: uploadErr } = await opts.sb.storage
    .from(BUCKET)
    .upload(objectPath, opts.content, {
      contentType: opts.contentType,
      upsert: opts.upsert,
    });

  const ok = !uploadErr;
  // Supabase JS doesn't expose the HTTP response code here. Use 200 for
  // success and 500 for failure — the audit row records intent (did the
  // upload land?), not transport-layer detail. Refine if Supabase ever
  // exposes a status field on UploadError.
  const httpStatus = ok ? 200 : 500;

  try {
    const { error: auditErr } = await opts.sb
      .from("audit_storage_writes")
      .insert({
        caller: opts.caller,
        organization_id: opts.organizationId,
        research_queue_id: opts.researchQueueId,
        object_path: objectPath,
        bytes: opts.content.length,
        http_status: httpStatus,
      });
    if (auditErr) {
      console.warn(
        `[storage-paths] audit_storage_writes insert failed (non-blocking): ${auditErr.message}`,
      );
    }
  } catch (auditEx) {
    console.warn(
      `[storage-paths] audit_storage_writes threw (non-blocking): ${
        (auditEx as Error).message
      }`,
    );
  }

  return ok
    ? { ok: true, path: objectPath }
    : {
        ok: false,
        path: objectPath,
        reason: uploadErr?.message ?? "unknown upload error",
      };
}
