/**
 * Phase B / S50 — frontend mirror of agent/lib/storage-paths.ts.
 *
 * The frontend is read-only against the research-projects bucket, so only
 * the path-construction helper is needed here. Uploads (and therefore the
 * audit hook) live entirely in `agent/`.
 *
 * Kept as a local mirror per v3 plan §2.7 file table ("Use scopedStoragePath()
 * helper from agent/lib (or a frontend-local mirror)") — agent/ and frontend/
 * have separate tsconfigs and avoiding the cross-package import keeps the Next
 * build hermetic.
 *
 * If this helper drifts from agent/lib/storage-paths.ts, the grep CI test in
 * `agent/scripts/test-phase-b-storage-paths.sh` will not catch it. Pair-edit
 * both files when changing the path scheme or the validation rules.
 */

// Strict canonical UUID v4 layout (8-4-4-4-12 hex). v1 used a looser
// 36-hex-with-dashes match (no layout enforcement) — accepted pathological
// strings like 36 consecutive hyphens (S50 Gemini MERGE M1).
const UUID_V4_REGEX = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

export function scopedStoragePath(
  orgId: string,
  projectSlug: string,
  file?: string,
): string {
  if (!orgId || !UUID_V4_REGEX.test(orgId)) {
    throw new Error(`scopedStoragePath: invalid orgId "${orgId}"`);
  }
  // Slug validation symmetric with filename validation below: reject "/",
  // "\", and ".." path-traversal components. The helper is the
  // tenant-boundary primitive; defense-in-depth even though slugs are
  // generated by generateSlug() today (Codex round-2 MINOR finding C-m1,
  // S56). Pair-edited with agent/lib/storage-paths.ts.
  if (
    !projectSlug ||
    projectSlug.includes("/") ||
    projectSlug.includes("\\") ||
    projectSlug.includes("..")
  ) {
    throw new Error(`scopedStoragePath: invalid slug "${projectSlug}"`);
  }
  // S50 Gemini MERGE C1 — defense-in-depth filename validation. Even where
  // an upstream Next API route already rejects path-traversal in the URL
  // segment (see api/runs/[slug]/file/[filename]/route.ts), keep the helper
  // strict so any new caller cannot accidentally serve a traversal path.
  if (file && (file.includes("/") || file.includes("\\") || file.includes(".."))) {
    throw new Error(`scopedStoragePath: invalid file name components "${file}"`);
  }
  return file ? `${orgId}/${projectSlug}/${file}` : `${orgId}/${projectSlug}`;
}
